Repository hmcts/ccd-next-hearing-date-updater, pull requests merged in 2023-02, with the labels that each got.

#112 HMAN-493 Enable cleanup of helm release on success
  Jenkinsfile_CNP
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-next-hearing-date-updater-pr-112

#138 HMAN-517 Bump version number of some HMCTS dependencies
  build.gradle
  charts/ccd-next-hearing-date-updater/Chart.yaml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ns:ccd, prd:ccd, rel:ccd-next-hearing-date-updater-pr-138

#153 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-next-hearing-date-updater-pr-153
