Repository hmcts/ccd-next-hearing-date-updater, pull requests merged in 2025-01, with the labels that each got.

#239 Fix shutdown issues
  charts/ccd-next-hearing-date-updater/Chart.yaml
  charts/ccd-next-hearing-date-updater/values.yaml
  lib/applicationinsights.json
Labels: ns:ccd, prd:ccd, rel:ccd-next-hearing-date-updater-pr-239

#240 Add `applicationinsights.json` to Dockerfile
  Dockerfile
Labels: ns:ccd, prd:ccd, rel:ccd-next-hearing-date-updater-pr-240

#238 CCD-5196:
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-next-hearing-date-updater-pr-238

#236 CCD 5923: fix CVE 2023 35116
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-next-hearing-date-updater-pr-236

#228 CCD-4975&CCD-4373
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-next-hearing-date-updater-pr-228
